/bin/bash: /home/ubuntu/miniconda/envs/fsdp/lib/libtinfo.so.6: no version information available (required by /bin/bash)
[2025-05-05 06:13:29,284] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 632, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/fsdp/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 796, in run
[2025-05-05 06:13:29,285] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 632, in determine_local_world_size
    config, cmd, cmd_args = config_from_args(args)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 701, in config_from_args
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/fsdp/bin/torchrun", line 8, in <module>
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 659, in determine_local_world_size
    sys.exit(main())
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") from e
ValueError: Unsupported nproc_per_node value: 
    run(args)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 796, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 701, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/ubuntu/miniconda/envs/fsdp/lib/python3.10/site-packages/torch/distributed/run.py", line 659, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") from e
ValueError: Unsupported nproc_per_node value: 
srun: error: 192-222-55-57: tasks 0-1: Exited with exit code 1
